### ISSUE TITLE
[Amazon](500310) Invalid operation when setting parameter to bpchar

### ISSUE THREAD

**Issue by braisCouce** [aws/amazon-redshift-jdbc-driver#15] opened 2021-03-22 15:43 UTC
## Driver version
2.0.0.3

## Redshift version
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.24421

## Client Operating System
Windows 10.

## JAVA/JVM version
Java 11.0.8

## Table schema
`CREATE TABLE parameters_bug (c_int integer, c_bpchar bpchar);`

## Problem description
We are receiving the error `[Amazon](500310) Invalid operation: Assert` using JDBC and prepared statements when we set a value to a field with type "bpchar" and the query has a GROUP BY.

To reproduce the issue execute next query from a JDBC client using parameters:
`SELECT c_int FROM parameters_bug WHERE c_bpchar = ? GROUP BY c_int;`

This issues happens with latest JDBC driver (2.0.0.3). Using 2.0.0.0 the query works fine. This issue has also been reported in [this AWS forum](https://forums.aws.amazon.com/thread.jspa?threadID=330922).

## JDBC trace logs
```
Detail: 
  -----------------------------------------------
  error:  Assert
  code:      1000
  context:   IsSDDisabled(m_dispatch_level) || num_compute_segments == 1 - Query with multi-segment stream cannot be selective dispatched
  query:     11508059
  location:  query.cpp:2073
  process:   padbmaster [pid=13121]
  -----------------------------------------------
  
com.amazon.redshift.util.RedshiftException: ERROR: Assert
  Detail: 
  -----------------------------------------------
  error:  Assert
  code:      1000
  context:   IsSDDisabled(m_dispatch_level) || num_compute_segments == 1 - Query with multi-segment stream cannot be selective dispatched
  query:     11508059
  location:  query.cpp:2073
  process:   padbmaster [pid=13121]


at com.amazon.redshift.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2579) ~[?:?]
	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResultsOnThread(QueryExecutorImpl.java:2253) ~[?:?]
	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1880) ~[?:?]
	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1872) ~[?:?]
	at com.amazon.redshift.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368) ~[?:?]
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeInternal(RedshiftStatementImpl.java:514) ~[?:?]
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.execute(RedshiftStatementImpl.java:435) ~[?:?]
	at com.amazon.redshift.jdbc.RedshiftPreparedStatement.executeWithFlags(RedshiftPreparedStatement.java:200) ~[?:?]
	at com.amazon.redshift.jdbc.RedshiftPreparedStatement.executeQuery(RedshiftPreparedStatement.java:115)
```

**Comment by iggarish** [comment] 2021-03-22 18:02
Thanks for reporting issue. We will take a look and get back to you.

**Comment by iggarish** [comment] 2021-03-23 22:43
We can reproduce to it. As you mention we fix one issue after 2.0.0.0, so server can do parameter conversion properly. So we can't revert that fix. But I start working with server team for this issue. This is not the driver issue. You can work around by setting this connection property: stringtype=varchar. But you may hit parameter conversion issue.

**Comment by braisCouce** [comment] 2021-03-24 08:04
Thanks for your quick response. Using 2.0.0.0 and 2.0.0.2 versions the issue does not happen, so I do not understand why it is a server issue instead of a driver issue. Does the server do something different depending on the driver version?

**Comment by iggarish** [comment] 2021-03-24 16:11
Ok. As I mention we had some param type conversion issue, so we change the code such that server will do require conversion. So now it takes different code path in server for execution. In this way, there must be some issue with BPCHAR in the server. If you see the exception it shows query.cpp file and line number, which is from server. So in short 2.0.0.0 and 2.0.0.3 driver takes different path in server execution because of parameter conversion change. Hope this answer your question. Have you tried work around I mention? i.e. add connection option in your url: "stringtype=varchar".

**Comment by braisCouce** [comment] 2021-03-24 17:03
Thanks for the explanation. Adding that property it works.

**Comment by iggarish** [comment] 2021-06-14 19:01
As this is server side issue and not the driver issue, closing the issue.

**Closed by iggarish** 2021-06-14 19:01 UTC
