### ISSUE TITLE
RedshiftConnectionImpl.isValid() can fail due to empty update statement

### ISSUE THREAD

**Issue by romanb** [aws/amazon-redshift-jdbc-driver#38] opened 2021-11-04 16:13 UTC
## Driver version
2.1.0.1

## Redshift version
See log output below.

## Client Operating System
Ubuntu 20.04.3

## JAVA/JVM version
openjdk version "13.0.7" 2021-04-20

## Problem description
Apparently the execution of `RedshiftConnectionImpl.isValid()` can fail due to the empty update statement [used here](https://github.com/aws/amazon-redshift-jdbc-driver/blob/master/src/main/java/com/amazon/redshift/jdbc/RedshiftConnectionImpl.java#L1682).

# JDBC trace logs
```
Nov 04 16:42:44.270 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.Driver.connect: ===================================
Nov 04 16:42:44.270 FUNCTION  [55 qtp1620459733-55] com.amazon.redshift.Driver.connect:  Enter (jdbc:redshift://<private>:5439/<private>?BlockingRowsMode=10000&enableFetchRingBuffer=false&LogLevel=5&LogPath=/tmp/redshift&LoginTimeout=10&SocketTimeout=10,{password=***, user=<private>}) 
Nov 04 16:42:44.271 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.Driver.connect: Connecting with URL: jdbc:redshift://<private>:5439/<private>?BlockingRowsMode=10000&enableFetchRingBuffer=false&LogLevel=5&LogPath=/tmp/redshift&LoginTimeout=10&SocketTimeout=10
Nov 04 16:42:44.271 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.jdbc.RedshiftConnectionImpl.RedshiftConnectionImpl: Redshift JDBC Driver 2.0.0.0
Nov 04 16:42:44.271 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.jdbc.RedshiftConnectionImpl.setDefaultFetchSize:   setDefaultFetchSize = 10,000
Nov 04 16:42:44.272 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.jdbc.RedshiftConnectionImpl.setPrepareThreshold:   setPrepareThreshold = 5
Nov 04 16:42:44.273 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.core.v3.ConnectionFactoryImpl.openConnectionImpl: Trying to establish a protocol version 3 connection to <private>:5439
Nov 04 16:42:44.303 INFO  [55 qtp1620459733-55] com.amazon.redshift.core.RedshiftStream.RedshiftStream: Gets a new stream on a new socket
Nov 04 16:42:44.303 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.core.v3.ConnectionFactoryImpl.tryConnect: Receive Buffer Size is 65,536
Nov 04 16:42:44.303 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.core.v3.ConnectionFactoryImpl.tryConnect: Send Buffer Size is 43,520
Nov 04 16:42:44.304 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.core.v3.ConnectionFactoryImpl.enableSSL:  FE=> SSLRequest
Nov 04 16:42:44.322 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.core.v3.ConnectionFactoryImpl.enableSSL:  <=BE SSLOk
Nov 04 16:42:44.420 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.core.v3.ConnectionFactoryImpl.sendStartupPacket:  FE=> StartupPacket(user=<private>, database=<private>, client_encoding=UTF8, DateStyle=ISO, TimeZone=Europe/Berlin, extra_float_digits=2, driver_version=Redshift JDBC Driver 2.0.0.0, os_version=Linux 5.11.0-38-generic amd64, client_protocol_version=3)
Nov 04 16:42:44.440 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.core.v3.ConnectionFactoryImpl.doAuthentication:  <=BE AuthenticationReqMD5
Nov 04 16:42:44.441 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.core.v3.ConnectionFactoryImpl.doAuthentication:  FE=> Password(md5digest)
Nov 04 16:42:44.462 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.core.v3.ConnectionFactoryImpl.doAuthentication:  <=BE AuthenticationOk
Nov 04 16:42:44.463 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.core.v3.QueryExecutorImpl.receiveParameterStatus:  <=BE ParameterStatus(application_name = unset)
Nov 04 16:42:44.463 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.core.v3.QueryExecutorImpl.receiveParameterStatus:  <=BE ParameterStatus(case_sensitive = on)
Nov 04 16:42:44.464 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.core.v3.QueryExecutorImpl.receiveParameterStatus:  <=BE ParameterStatus(client_encoding = UTF8)
Nov 04 16:42:44.465 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.core.v3.QueryExecutorImpl.receiveParameterStatus:  <=BE ParameterStatus(datestyle = ISO, MDY)
Nov 04 16:42:44.465 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.core.v3.QueryExecutorImpl.receiveParameterStatus:  <=BE ParameterStatus(integer_datetimes = on)
Nov 04 16:42:44.465 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.core.v3.QueryExecutorImpl.receiveParameterStatus:  <=BE ParameterStatus(is_superuser = off)
Nov 04 16:42:44.466 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.core.v3.QueryExecutorImpl.receiveParameterStatus:  <=BE ParameterStatus(server_encoding = UNICODE)
Nov 04 16:42:44.466 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.core.v3.QueryExecutorImpl.receiveParameterStatus:  <=BE ParameterStatus(server_version = 8.0.2)
Nov 04 16:42:44.467 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.core.v3.QueryExecutorImpl.receiveParameterStatus:  <=BE ParameterStatus(session_authorization = <private>)
Nov 04 16:42:44.467 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.core.v3.QueryExecutorImpl.receiveParameterStatus:  <=BE ParameterStatus(TimeZone = Europe/Berlin)
Nov 04 16:42:44.468 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.core.v3.QueryExecutorImpl.receiveParameterStatus:  <=BE ParameterStatus(timezone_abbreviations = Default)
Nov 04 16:42:44.468 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.core.v3.QueryExecutorImpl.receiveParameterStatus:  <=BE ParameterStatus(padb_version = 1.0.32574)
Nov 04 16:42:44.469 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.core.v3.QueryExecutorImpl.receiveParameterStatus:  <=BE ParameterStatus(padb_revision = 47ce08e2f2)
Nov 04 16:42:44.469 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.core.v3.QueryExecutorImpl.receiveParameterStatus:  <=BE ParameterStatus(max_numeric_precision = 38)
Nov 04 16:42:44.470 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.core.v3.QueryExecutorImpl.receiveParameterStatus:  <=BE ParameterStatus(max_varchar_size = 65535)
Nov 04 16:42:44.470 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.core.v3.QueryExecutorImpl.receiveParameterStatus:  <=BE ParameterStatus(datashare_enabled = on)
Nov 04 16:42:44.471 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.core.v3.QueryExecutorImpl.receiveParameterStatus:  <=BE ParameterStatus(session_id = 6dcde04e-c76d-42c7-80a1-4e4018f93881)
Nov 04 16:42:44.472 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.core.v3.QueryExecutorImpl.receiveParameterStatus:  <=BE ParameterStatus(server_protocol_version = 2)
Nov 04 16:42:44.472 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.core.v3.QueryExecutorImpl.readStartupMessages:  <=BE BackendKeyData(pid=30,037,ckey=871,863,009)
Nov 04 16:42:44.473 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.core.v3.QueryExecutorImpl.receiveRFQ:  <=BE ReadyForQuery(I)
Nov 04 16:42:44.474 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.jdbc.RedshiftConnectionImpl.RedshiftConnectionImpl:     types using binary send = TIMESTAMPTZ,UUID,INT2_ARRAY,INT4_ARRAY,BYTEA,TEXT_ARRAY,TIMETZ,INT8,INT2,INT4,VARCHAR_ARRAY,INT8_ARRAY,POINT,TIMESTAMP,TIME,BOX,FLOAT4,FLOAT8,FLOAT4_ARRAY,FLOAT8_ARRAY
Nov 04 16:42:44.474 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.jdbc.RedshiftConnectionImpl.RedshiftConnectionImpl:     types using binary receive = TIMESTAMPTZ,UUID,INT2_ARRAY,INT4_ARRAY,BYTEA,TEXT_ARRAY,TIMETZ,INT8,INT2,INT4,VARCHAR_ARRAY,INT8_ARRAY,POINT,DATE,TIMESTAMP,TIME,BOX,FLOAT4,FLOAT8,FLOAT4_ARRAY,FLOAT8_ARRAY
Nov 04 16:42:44.474 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.jdbc.RedshiftConnectionImpl.RedshiftConnectionImpl:     integer date/time = true
Nov 04 16:42:44.475 FUNCTION  [55 qtp1620459733-55] com.amazon.redshift.Driver.connect:  Return com.amazon.redshift.jdbc.RedshiftConnectionImpl@2afe9287 
Nov 04 16:42:44.475 FUNCTION  [55 qtp1620459733-55] com.amazon.redshift.jdbc.RedshiftConnectionImpl.setNetworkTimeout:  Enter (null,2000) 
Nov 04 16:42:44.475 FUNCTION  [55 qtp1620459733-55] com.amazon.redshift.jdbc.RedshiftConnectionImpl.setNetworkTimeout:  Return  
Nov 04 16:42:44.476 FUNCTION  [55 qtp1620459733-55] com.amazon.redshift.jdbc.RedshiftConnectionImpl.prepareStatement:  Enter () 
Nov 04 16:42:44.476 FUNCTION  [55 qtp1620459733-55] com.amazon.redshift.jdbc.RedshiftConnectionImpl.prepareStatement:  Enter (,1003,1007) 
Nov 04 16:42:44.476 FUNCTION  [55 qtp1620459733-55] com.amazon.redshift.jdbc.RedshiftConnectionImpl.prepareStatement:  Enter (,1003,1007,2) 
Nov 04 16:42:44.476 FUNCTION  [55 qtp1620459733-55] com.amazon.redshift.jdbc.RedshiftStatementImpl.setFetchSize:  Enter (10000) 
Nov 04 16:42:44.476 FUNCTION  [55 qtp1620459733-55] com.amazon.redshift.jdbc.RedshiftStatementImpl.setFetchSize:  Return  
Nov 04 16:42:44.477 FUNCTION  [55 qtp1620459733-55] com.amazon.redshift.jdbc.RedshiftStatementImpl.setPoolable:  Enter (true) 
Nov 04 16:42:44.477 FUNCTION  [55 qtp1620459733-55] com.amazon.redshift.jdbc.RedshiftConnectionImpl.prepareStatement:  Return  
Nov 04 16:42:44.477 FUNCTION  [55 qtp1620459733-55] com.amazon.redshift.jdbc.RedshiftConnectionImpl.prepareStatement:  Return  
Nov 04 16:42:44.477 FUNCTION  [55 qtp1620459733-55] com.amazon.redshift.jdbc.RedshiftConnectionImpl.prepareStatement:  Return  
Nov 04 16:42:44.478 FUNCTION  [55 qtp1620459733-55] com.amazon.redshift.jdbc.RedshiftStatementImpl.setQueryTimeout:  Enter (2) 
Nov 04 16:42:44.478 FUNCTION  [55 qtp1620459733-55] com.amazon.redshift.jdbc.RedshiftPreparedStatement.executeUpdate:  Enter () 
Nov 04 16:42:44.478 FUNCTION  [55 qtp1620459733-55] com.amazon.redshift.jdbc.RedshiftConnectionImpl.getAutoCommit:  Enter () 
Nov 04 16:42:44.479 FUNCTION  [55 qtp1620459733-55] com.amazon.redshift.jdbc.RedshiftConnectionImpl.getAutoCommit:  Return true 
Nov 04 16:42:44.479 FUNCTION  [55 qtp1620459733-55] com.amazon.redshift.jdbc.RedshiftConnectionImpl.getAutoCommit:  Enter () 
Nov 04 16:42:44.479 FUNCTION  [55 qtp1620459733-55] com.amazon.redshift.jdbc.RedshiftConnectionImpl.getAutoCommit:  Return true 
Nov 04 16:42:44.480 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.core.v3.QueryExecutorImpl.execute:   simple execute, handler=com.amazon.redshift.jdbc.RedshiftStatementImpl$StatementResultHandler@ba06dff, maxRows=0, fetchSize=10,000, flags=20
Nov 04 16:42:44.481 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.core.v3.QueryExecutorImpl.sendParse:  FE=> Parse(stmt=S_1-22893211762112,query="",oids={})
Nov 04 16:42:44.482 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.core.v3.QueryExecutorImpl.sendBind:  FE=> Bind(stmt=S_1-22893211762112,portal=C_2-22893212308134)
Nov 04 16:42:44.482 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.core.v3.QueryExecutorImpl.sendDescribePortal:  FE=> Describe(portal=C_2-22893212308134)
Nov 04 16:42:44.483 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.core.v3.QueryExecutorImpl.sendExecute:  FE=> Execute(portal=C_2-22893212308134,limit=1)
Nov 04 16:42:44.483 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.core.v3.QueryExecutorImpl.sendFlush:  FE=> Flush
Nov 04 16:42:44.484 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.core.v3.QueryExecutorImpl.sendSync:  FE=> Sync
Nov 04 16:42:44.605 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.core.v3.QueryExecutorImpl.processResultsOnThread:  <=BE ParseComplete [S_1-22893211762112]
Nov 04 16:42:44.619 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.core.v3.QueryExecutorImpl.receiveErrorResponse:  <=BE ErrorMessage(ERROR: Assert
  Detail: 
  -----------------------------------------------
  error:  Assert
  code:      1000
  context:   query_text != NULL && query_text[0] != '\0' - The query text must be non empty for PG_START record
  query:     0
  location:  monitoring_pg_query.cpp:446
  process:   padbmaster [pid=30037]
  -----------------------------------------------

  Location: File: /home/ec2-user/padb/src/sys/xen_execute.cpp, Routine: pg_throw, Line: 9989
  Server SQLState: XX000)
Nov 04 16:42:44.620 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.core.v3.QueryExecutorImpl.receiveRFQ:  <=BE ReadyForQuery(I)
Nov 04 16:42:44.620 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.core.v3.QueryExecutorImpl.processResultsOnThread:  FE marking setPortalDescribed(false) for query 
Nov 04 16:42:44.621 DEBUG  [55 qtp1620459733-55] com.amazon.redshift.core.v3.QueryExecutorImpl.processResultsOnThread:  FE marking setPortalDescribed(false) for query SYNC
Nov 04 16:42:44.622 ERROR  [55 qtp1620459733-55] com.amazon.redshift.core.v3.QueryExecutorImpl.rollbackIfRequired: com.amazon.redshift.util.RedshiftException: ERROR: Assert
  Detail: 
  -----------------------------------------------
  error:  Assert
  code:      1000
  context:   query_text != NULL && query_text[0] != '\0' - The query text must be non empty for PG_START record
  query:     0
  location:  monitoring_pg_query.cpp:446
  process:   padbmaster [pid=30037]
  -----------------------------------------------

	at com.amazon.redshift.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2601)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResultsOnThread(QueryExecutorImpl.java:2269)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1880)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1872)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeInternal(RedshiftStatementImpl.java:514)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.execute(RedshiftStatementImpl.java:435)
	at com.amazon.redshift.jdbc.RedshiftPreparedStatement.executeWithFlags(RedshiftPreparedStatement.java:200)
	at com.amazon.redshift.jdbc.RedshiftPreparedStatement.executeUpdate(RedshiftPreparedStatement.java:142)
	at com.amazon.redshift.jdbc.RedshiftConnectionImpl.isValid(RedshiftConnectionImpl.java:1687)
    at <private>
```

# Suggestion

Rather than an empty query string, `SELECT 1` could be used in combination with `execute()` or `executeQuery()`. That seems to avoid the problem.

**Comment by iggarish** [comment] 2021-11-04 16:59
This is known regression in the server side. Sever team has fix and will release the patch soon. Empty string is a valid as per the protocol. The driver is not executing any other statement as you mention because it doesn't want to interfere user's transaction.

**Comment by iggarish** [comment] 2021-11-04 17:00
This is not the driver issue, so closing the issue.

**Closed by iggarish** 2021-11-04 17:00 UTC

**Comment by romanb** [comment] 2021-11-08 10:48
> This is known regression in the server side. Sever team has fix and will release the patch soon.

Is there any public place where progress on that issue can be seen or where the patch will be announced, so that we would know when to try again?

**Comment by iggarish** [comment] 2021-11-08 23:31
You need to create a support ticket with Redshift. That way you can track it. Sorry we don't have server code/bugs accessible like for the driver. But next patch of Redshift will have fix for it for sure.
